// Generated by jextract

package pe.pi.v4l2reader.mediaApi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     ALG_SENSOR_DEFAULT_S stSnsDft;
 *     ALG_SENSOR_EXP_FUNC_S stSnsExp;
 *     ALG_LENS_FUNC_S stLensFunc;
 * }
 * }
 */
public class AML_ALG_CTX_S {

    AML_ALG_CTX_S() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ALG_SENSOR_DEFAULT_S.layout().withName("stSnsDft"),
        ALG_SENSOR_EXP_FUNC_S.layout().withName("stSnsExp"),
        ALG_LENS_FUNC_S.layout().withName("stLensFunc")
    ).withName("$anon$130:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout stSnsDft$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stSnsDft"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ALG_SENSOR_DEFAULT_S stSnsDft
     * }
     */
    public static final GroupLayout stSnsDft$layout() {
        return stSnsDft$LAYOUT;
    }

    private static final long stSnsDft$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ALG_SENSOR_DEFAULT_S stSnsDft
     * }
     */
    public static final long stSnsDft$offset() {
        return stSnsDft$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ALG_SENSOR_DEFAULT_S stSnsDft
     * }
     */
    public static MemorySegment stSnsDft(MemorySegment struct) {
        return struct.asSlice(stSnsDft$OFFSET, stSnsDft$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ALG_SENSOR_DEFAULT_S stSnsDft
     * }
     */
    public static void stSnsDft(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stSnsDft$OFFSET, stSnsDft$LAYOUT.byteSize());
    }

    private static final GroupLayout stSnsExp$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stSnsExp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ALG_SENSOR_EXP_FUNC_S stSnsExp
     * }
     */
    public static final GroupLayout stSnsExp$layout() {
        return stSnsExp$LAYOUT;
    }

    private static final long stSnsExp$OFFSET = 240;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ALG_SENSOR_EXP_FUNC_S stSnsExp
     * }
     */
    public static final long stSnsExp$offset() {
        return stSnsExp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ALG_SENSOR_EXP_FUNC_S stSnsExp
     * }
     */
    public static MemorySegment stSnsExp(MemorySegment struct) {
        return struct.asSlice(stSnsExp$OFFSET, stSnsExp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ALG_SENSOR_EXP_FUNC_S stSnsExp
     * }
     */
    public static void stSnsExp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stSnsExp$OFFSET, stSnsExp$LAYOUT.byteSize());
    }

    private static final GroupLayout stLensFunc$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stLensFunc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ALG_LENS_FUNC_S stLensFunc
     * }
     */
    public static final GroupLayout stLensFunc$layout() {
        return stLensFunc$LAYOUT;
    }

    private static final long stLensFunc$OFFSET = 288;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ALG_LENS_FUNC_S stLensFunc
     * }
     */
    public static final long stLensFunc$offset() {
        return stLensFunc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ALG_LENS_FUNC_S stLensFunc
     * }
     */
    public static MemorySegment stLensFunc(MemorySegment struct) {
        return struct.asSlice(stLensFunc$OFFSET, stLensFunc$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ALG_LENS_FUNC_S stLensFunc
     * }
     */
    public static void stLensFunc(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stLensFunc$OFFSET, stLensFunc$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

