// Generated by jextract

package pe.pi.v4l2reader.mediaApi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _image_resolution_t {
 *     uint32_t width;
 *     uint32_t height;
 * } image_resolution_t
 * }
 */
public class image_resolution_t extends _image_resolution_t {

    image_resolution_t() {
        // Should not be called directly
    }
}

