// Generated by jextract

package pe.pi.v4l2reader.mediaApi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class mediaAPI extends mediaAPI_1 {

    mediaAPI() {
        // Should not be called directly
    }
    private static final int V4L2_CID_AML_MODE = (int)9967876L;
    /**
     * {@snippet lang=c :
     * #define V4L2_CID_AML_MODE 9967876
     * }
     */
    public static int V4L2_CID_AML_MODE() {
        return V4L2_CID_AML_MODE;
    }
    private static final int V4L2_CID_AML_LENS_MOVING = (int)9967878L;
    /**
     * {@snippet lang=c :
     * #define V4L2_CID_AML_LENS_MOVING 9967878
     * }
     */
    public static int V4L2_CID_AML_LENS_MOVING() {
        return V4L2_CID_AML_LENS_MOVING;
    }
    private static final int V4L2_META_AML_ISP_CONFIG = (int)1195787073L;
    /**
     * {@snippet lang=c :
     * #define V4L2_META_AML_ISP_CONFIG 1195787073
     * }
     */
    public static int V4L2_META_AML_ISP_CONFIG() {
        return V4L2_META_AML_ISP_CONFIG;
    }
    private static final int V4L2_META_AML_ISP_STATS = (int)1398035265L;
    /**
     * {@snippet lang=c :
     * #define V4L2_META_AML_ISP_STATS 1398035265
     * }
     */
    public static int V4L2_META_AML_ISP_STATS() {
        return V4L2_META_AML_ISP_STATS;
    }
}

