// Generated by jextract

package pe.pi.v4l2reader.mediaApi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct stream_configuration {
 *     struct aml_format format;
 *     struct aml_format vformat[4];
 * }
 * }
 */
public class stream_configuration {

    stream_configuration() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        aml_format.layout().withName("format"),
        MemoryLayout.sequenceLayout(4, aml_format.layout()).withName("vformat")
    ).withName("stream_configuration");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout format$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct aml_format format
     * }
     */
    public static final GroupLayout format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct aml_format format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct aml_format format
     * }
     */
    public static MemorySegment format(MemorySegment struct) {
        return struct.asSlice(format$OFFSET, format$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct aml_format format
     * }
     */
    public static void format(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, format$OFFSET, format$LAYOUT.byteSize());
    }

    private static final SequenceLayout vformat$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("vformat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct aml_format vformat[4]
     * }
     */
    public static final SequenceLayout vformat$layout() {
        return vformat$LAYOUT;
    }

    private static final long vformat$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct aml_format vformat[4]
     * }
     */
    public static final long vformat$offset() {
        return vformat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct aml_format vformat[4]
     * }
     */
    public static MemorySegment vformat(MemorySegment struct) {
        return struct.asSlice(vformat$OFFSET, vformat$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct aml_format vformat[4]
     * }
     */
    public static void vformat(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, vformat$OFFSET, vformat$LAYOUT.byteSize());
    }

    private static long[] vformat$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * struct aml_format vformat[4]
     * }
     */
    public static long[] vformat$dimensions() {
        return vformat$DIMS;
    }
    private static final MethodHandle vformat$ELEM_HANDLE = vformat$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * struct aml_format vformat[4]
     * }
     */
    public static MemorySegment vformat(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)vformat$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * struct aml_format vformat[4]
     * }
     */
    public static void vformat(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, vformat(struct, index0), 0L, aml_format.layout().byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

