// Generated by jextract

package pe.pi.v4l2reader.mediaApi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct v4l2_plane_pix_format {
 *     __u32 sizeimage;
 *     __u32 bytesperline;
 *     __u16 reserved[6];
 * }
 * }
 */
public class v4l2_plane_pix_format {

    v4l2_plane_pix_format() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        mediaAPI.align(mediaAPI.C_INT, 1).withName("sizeimage"),
        mediaAPI.align(mediaAPI.C_INT, 1).withName("bytesperline"),
        MemoryLayout.sequenceLayout(6, mediaAPI.align(mediaAPI.C_SHORT, 1)).withName("reserved")
    ).withName("v4l2_plane_pix_format");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sizeimage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sizeimage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 sizeimage
     * }
     */
    public static final OfInt sizeimage$layout() {
        return sizeimage$LAYOUT;
    }

    private static final long sizeimage$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 sizeimage
     * }
     */
    public static final long sizeimage$offset() {
        return sizeimage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 sizeimage
     * }
     */
    public static int sizeimage(MemorySegment struct) {
        return struct.get(sizeimage$LAYOUT, sizeimage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 sizeimage
     * }
     */
    public static void sizeimage(MemorySegment struct, int fieldValue) {
        struct.set(sizeimage$LAYOUT, sizeimage$OFFSET, fieldValue);
    }

    private static final OfInt bytesperline$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bytesperline"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 bytesperline
     * }
     */
    public static final OfInt bytesperline$layout() {
        return bytesperline$LAYOUT;
    }

    private static final long bytesperline$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 bytesperline
     * }
     */
    public static final long bytesperline$offset() {
        return bytesperline$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 bytesperline
     * }
     */
    public static int bytesperline(MemorySegment struct) {
        return struct.get(bytesperline$LAYOUT, bytesperline$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 bytesperline
     * }
     */
    public static void bytesperline(MemorySegment struct, int fieldValue) {
        struct.set(bytesperline$LAYOUT, bytesperline$OFFSET, fieldValue);
    }

    private static final SequenceLayout reserved$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u16 reserved[6]
     * }
     */
    public static final SequenceLayout reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u16 reserved[6]
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u16 reserved[6]
     * }
     */
    public static MemorySegment reserved(MemorySegment struct) {
        return struct.asSlice(reserved$OFFSET, reserved$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u16 reserved[6]
     * }
     */
    public static void reserved(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, reserved$OFFSET, reserved$LAYOUT.byteSize());
    }

    private static long[] reserved$DIMS = { 6 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u16 reserved[6]
     * }
     */
    public static long[] reserved$dimensions() {
        return reserved$DIMS;
    }
    private static final VarHandle reserved$ELEM_HANDLE = reserved$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u16 reserved[6]
     * }
     */
    public static short reserved(MemorySegment struct, long index0) {
        return (short)reserved$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u16 reserved[6]
     * }
     */
    public static void reserved(MemorySegment struct, long index0, short fieldValue) {
        reserved$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

