// Generated by jextract

package pe.pi.v4l2reader.mediaApi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct v4l2_sdr_format {
 *     __u32 pixelformat;
 *     __u32 buffersize;
 *     __u8 reserved[24];
 * }
 * }
 */
public class v4l2_sdr_format {

    v4l2_sdr_format() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        mediaAPI.align(mediaAPI.C_INT, 1).withName("pixelformat"),
        mediaAPI.align(mediaAPI.C_INT, 1).withName("buffersize"),
        MemoryLayout.sequenceLayout(24, mediaAPI.C_CHAR).withName("reserved")
    ).withName("v4l2_sdr_format");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt pixelformat$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pixelformat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 pixelformat
     * }
     */
    public static final OfInt pixelformat$layout() {
        return pixelformat$LAYOUT;
    }

    private static final long pixelformat$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 pixelformat
     * }
     */
    public static final long pixelformat$offset() {
        return pixelformat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 pixelformat
     * }
     */
    public static int pixelformat(MemorySegment struct) {
        return struct.get(pixelformat$LAYOUT, pixelformat$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 pixelformat
     * }
     */
    public static void pixelformat(MemorySegment struct, int fieldValue) {
        struct.set(pixelformat$LAYOUT, pixelformat$OFFSET, fieldValue);
    }

    private static final OfInt buffersize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("buffersize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 buffersize
     * }
     */
    public static final OfInt buffersize$layout() {
        return buffersize$LAYOUT;
    }

    private static final long buffersize$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 buffersize
     * }
     */
    public static final long buffersize$offset() {
        return buffersize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 buffersize
     * }
     */
    public static int buffersize(MemorySegment struct) {
        return struct.get(buffersize$LAYOUT, buffersize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 buffersize
     * }
     */
    public static void buffersize(MemorySegment struct, int fieldValue) {
        struct.set(buffersize$LAYOUT, buffersize$OFFSET, fieldValue);
    }

    private static final SequenceLayout reserved$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u8 reserved[24]
     * }
     */
    public static final SequenceLayout reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u8 reserved[24]
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u8 reserved[24]
     * }
     */
    public static MemorySegment reserved(MemorySegment struct) {
        return struct.asSlice(reserved$OFFSET, reserved$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u8 reserved[24]
     * }
     */
    public static void reserved(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, reserved$OFFSET, reserved$LAYOUT.byteSize());
    }

    private static long[] reserved$DIMS = { 24 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u8 reserved[24]
     * }
     */
    public static long[] reserved$dimensions() {
        return reserved$DIMS;
    }
    private static final VarHandle reserved$ELEM_HANDLE = reserved$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u8 reserved[24]
     * }
     */
    public static byte reserved(MemorySegment struct, long index0) {
        return (byte)reserved$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u8 reserved[24]
     * }
     */
    public static void reserved(MemorySegment struct, long index0, byte fieldValue) {
        reserved$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

